site_name: 'Template Documentation'
nav:
  - Overview: index.md
  - Prerequisites: template-prerequisites.md
  - Template Usage: usage.md
  - Deployed Application: application.md
plugins:
  - techdocs-core
