apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: rhtap-dev-namespace-setup-
spec:
  pipelineSpec:
    tasks:
      - name: configure-namespace
        taskRef:
          kind: Task
          params:
            - name: kind
              value: task
            - name: name
              value: rhtap-dev-namespace-setup
            - name: namespace
              value: ${{ values.rhtapNamespace }}
          resolver: cluster