#!/bin/bash

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" 
ROOTDIR=$(realpath $SCRIPTDIR/..)
source $ROOTDIR/properties

REPO="${PIPELINE_REPO:-https://github.com/redhat-ai-dev/rhdh-pipelines}"
BRANCH="${PIPELINE_BRANCH:-main}"
RAW_BASE=$(echo $REPO/$BRANCH |  sed "s/github.com/raw.githubusercontent.com/")  
REPONAME=$(basename $REPO)

TEMPDIR=$ROOTDIR/temp
rm -rf $TEMPDIR # clean up
mkdir -p $TEMPDIR
cd $TEMPDIR
git clone $REPO 2>&1 > /dev/null
(cd $REPONAME; git checkout $BRANCH; git pull)

function add-backstage-labels () { 
        FILE_NAME=$1
        
        # if using darwin (macos)
        if ! sed --version >/dev/null 2>&1; then
                # replace {{values.rawUrl}} to the current commit's URL
                sed -i '' "s!{{values.rawUrl}}!$RAW_BASE!g" $FILE_NAME
                sed -i '' "s!{{ values!\${{ values!g" $FILE_NAME
        # if using linux
        else
                # replace {{values.rawUrl}} to the current commit's URL
                sed -i "s!{{values.rawUrl}}!$RAW_BASE!g" $FILE_NAME
                sed -i "s!{{ values!\${{ values!g" $FILE_NAME
        fi

        # add labels for RHDH
        yq -i '(. | .metadata.labels += { "argocd/app-name": "${{ values.name }}",
                "janus-idp.io/tekton": "${{ values.name }}", 
                "backstage.io/kubernetes-id": "${{ values.name }}",
                "backstage.io/kubernetes-namespace": "${{ values.namespace }}",
                "app.kubernetes.io/part-of": "${{ values.name }}"
                } )' $FILE_NAME     
}

#source and gitops tekton copied, note new names 
SRC_TEKTON=$ROOTDIR/skeleton/source-repo/.tekton

rm -rf $SRC_TEKTON
mkdir -p $SRC_TEKTON   
cp -r $TEMPDIR/$REPONAME/pac/source-repo/. $SRC_TEKTON
rm -rf $TEMPDIR
 
for prun in $SRC_TEKTON/*.yaml; do 
        echo "Labels for $prun" 
        add-backstage-labels $prun
done 
 