#!/bin/bash

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" 
ROOT_DIR=$(realpath $SCRIPTDIR/..)
SKELETON_DIR=$ROOT_DIR/skeleton
TEMPLATE_DIR=$ROOT_DIR/templates

function apply-configurations() {
    DEST=$1
    SAMPLENAME=$2
    TEMPLATE_TECHDOC_TYPE=$3

    DOC_SRC_ROOT="$ROOT_DIR/documentation/$TEMPLATE_TECHDOC_TYPE"

    # documentation (sample, prerequisites, remote cluster)
    SAMPLE_DOC_SRC="$DOC_SRC_ROOT/$SAMPLENAME"
    PREREQ_DOC_SRC="$DOC_SRC_ROOT/template-prerequisites.md"
    REMOTE_DOC_SRC="$DOC_SRC_ROOT/template-remote-cluster.md"
    if [ -d $DOC_SRC_ROOT ]; then
        if [ -d $SAMPLE_DOC_SRC ]; then
            cp -r $SAMPLE_DOC_SRC $DEST/docs
            if [ -f $PREREQ_DOC_SRC ]; then
                cp $PREREQ_DOC_SRC $DEST/docs/template-prerequisites.md
            fi
            if [ -f $REMOTE_DOC_SRC ]; then
                cp $REMOTE_DOC_SRC $DEST/docs/template-remote-cluster.md
            fi
        fi
        cp -r $DOC_SRC_ROOT/mkdocs.yml $DEST/mkdocs.yml
    fi

    cp $SKELETON_DIR/template.yaml $DEST/template.yaml

    # get default env variables
    source $SCRIPTDIR/envs/base

    # get sample env variables
    source $SCRIPTDIR/envs/$SAMPLENAME

    # if using darwin (macos)
    if ! sed --version >/dev/null 2>&1; then
        if [ -f $f/Containerfile ]; then
            sed -i '' "s!sed.edit.DOCKERFILE!Containerfile!g" $DEST/template.yaml
            sed -i '' "s!sed.edit.BUILDCONTEXT!.!g" $DEST/template.yaml
        fi

        sed -i '' "s!sed.edit.APP_NAME!$APP_NAME!g" $DEST/template.yaml
        sed -i '' "s!sed.edit.APP_DISPLAY_NAME!$APP_DISPLAY_NAME!g" $DEST/template.yaml
        sed -i '' "s!sed.edit.DESCRIPTION!$APP_DESC!g" $DEST/template.yaml
        sed -i '' "s!sed.edit.APPTAGS!$APP_TAGS!g" $DEST/template.yaml
        sed -i '' "s!sed.edit.CATALOG_DESCRIPTION!Secure Supply Chain Example for $APP_DISPLAY_NAME!g" $DEST/template.yaml
        sed -i '' "s!sed.edit.OWNER!$OWNER!g" $DEST/template.yaml

        if [ $SUPPORT_APP == false ]; then
            sed -i '' '/# SED_APP_SUPPORT_START/,/# SED_APP_SUPPORT_END/d' $DEST/template.yaml
        fi
        if [ $SUPPORT_LLM == false ]; then
            sed -i '' '/# SED_LLM_SERVER_START/,/# SED_LLM_SERVER_END/d' $DEST/template.yaml
        fi
        if [ $SUPPORT_LLM_LLAMA == false ]; then
            sed -i '' '/# SED_LLM_LLAMA_SERVER_START/,/# SED_LLM_LLAMA_SERVER_END/d' $DEST/template.yaml
            sed -i '' 's/llama.cpp: ${MODEL_SERVICE_DESC}. | \[Learn more\][(]${MODEL_SERVICE_SRC}[)]//' $DEST/template.yaml
        fi
        if [ $SUPPORT_ASR == false ]; then
            sed -i '' '/# SED_ASR_MODEL_SERVER_START/,/# SED_ASR_MODEL_SERVER_END/d' $DEST/template.yaml
        fi
        if [ $SUPPORT_DETR == false ]; then
            sed -i '' '/# SED_DETR_MODEL_SERVER_START/,/# SED_DETR_MODEL_SERVER_END/d' $DEST/template.yaml
        fi
        if [ $SUPPORT_DB == false ]; then
            sed -i '' '/# SED_DB_START/,/# SED_DB_END/d' $DEST/template.yaml
        fi
        if [ $SUPPORT_EXISTING == false ]; then
            sed -i '' '/# SED_EXISTING_START/,/# SED_EXISTING_END/d' $DEST/template.yaml
        fi
        if [ $SUPPORT_EXISTING_SERVER == false ]; then
            sed -i '' '/# SED_EXISTING_SERVER_START/,/# SED_EXISTING_SERVER_END/d' $DEST/template.yaml
        fi
        if [ $SUPPORT_MODEL_CATALOG == false ]; then
            sed -i '' '/# SED_EXISTING_FROM_CATALOG_START/,/# SED_EXISTING_FROM_CATALOG_END/d' $DEST/template.yaml
        fi
    # if using linux
    else
        if [ -f $f/Containerfile ]; then
            sed -i "s!sed.edit.DOCKERFILE!Containerfile!g" $DEST/template.yaml
            sed -i "s!sed.edit.BUILDCONTEXT!.!g" $DEST/template.yaml
        fi

        sed -i "s!sed.edit.APP_NAME!$APP_NAME!g" $DEST/template.yaml
        sed -i "s!sed.edit.APP_DISPLAY_NAME!$APP_DISPLAY_NAME!g" $DEST/template.yaml
        sed -i "s!sed.edit.DESCRIPTION!$APP_DESC!g" $DEST/template.yaml
        sed -i "s!sed.edit.APPTAGS!$APP_TAGS!g" $DEST/template.yaml
        sed -i "s!sed.edit.CATALOG_DESCRIPTION!Secure Supply Chain Example for $APP_DISPLAY_NAME!g" $DEST/template.yaml
        sed -i "s!sed.edit.OWNER!$OWNER!g" $DEST/template.yaml

        if [ $SUPPORT_APP == false ]; then
            sed -i '/# SED_APP_SUPPORT_START/,/# SED_APP_SUPPORT_END/d' $DEST/template.yaml
        fi
        if [ $SUPPORT_LLM == false ]; then
            sed -i '/# SED_LLM_SERVER_START/,/# SED_LLM_SERVER_END/d' $DEST/template.yaml
        fi
        if [ $SUPPORT_LLM_LLAMA == false ]; then
            sed -i '/# SED_LLM_LLAMA_SERVER_START/,/# SED_LLM_LLAMA_SERVER_END/d' $DEST/template.yaml
            sed -i 's/llama.cpp: ${MODEL_SERVICE_DESC}. | \[Learn more\][(]${MODEL_SERVICE_SRC}[)]//' $DEST/template.yaml
        fi
        if [ $SUPPORT_ASR == false ]; then
            sed -i '/# SED_ASR_MODEL_SERVER_START/,/# SED_ASR_MODEL_SERVER_END/d' $DEST/template.yaml
        fi
        if [ $SUPPORT_DETR == false ]; then
            sed -i '/# SED_DETR_MODEL_SERVER_START/,/# SED_DETR_MODEL_SERVER_END/d' $DEST/template.yaml
        fi
        if [ $SUPPORT_DB == false ]; then
            sed -i '/# SED_DB_START/,/# SED_DB_END/d' $DEST/template.yaml
        fi
        if [ $SUPPORT_EXISTING == false ]; then
            sed -i '/# SED_EXISTING_START/,/# SED_EXISTING_END/d' $DEST/template.yaml
        fi
        if [ $SUPPORT_EXISTING_SERVER == false ]; then
            sed -i '/# SED_EXISTING_SERVER_START/,/# SED_EXISTING_SERVER_END/d' $DEST/template.yaml
        fi
        if [ $SUPPORT_MODEL_CATALOG == false ]; then
            sed -i '/# SED_EXISTING_FROM_CATALOG_START/,/# SED_EXISTING_FROM_CATALOG_END/d' $DEST/template.yaml
        fi
    fi

    source $ROOT_DIR/properties
    cat $DEST/template.yaml | envsubst >$DEST/new-template.yaml
    mv $DEST/new-template.yaml $DEST/template.yaml
}
